# Generated by Django 2.2.24 on 2022-08-13 11:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_class',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], max_length=10, null=True),
        ),
    ]
