# Generated by Django 3.2.8 on 2021-11-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20211123_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcreate',
            old_name='teacher',
            new_name='teacher_create',
        ),
        migrations.RenameField(
            model_name='assignmentsubmit',
            old_name='student',
            new_name='student_submit',
        ),
    ]
