# Generated by Django 2.2.24 on 2022-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Teacher'), (2, 'Admin')], null=True),
        ),
    ]
