# Generated by Django 2.2.24 on 2022-08-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP',
            new_name='OTPModels',
        ),
    ]
