# Generated by Django 3.2.8 on 2021-11-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20211123_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcreate',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='assignmentsubmit',
            old_name='submited_data',
            new_name='submited_date',
        ),
    ]
