# Generated by Django 3.2.8 on 2021-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='rojina', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
