# Generated by Django 3.2.8 on 2021-11-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
