# Generated by Django 3.2.8 on 2021-11-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20211123_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcreate',
            name='subject_create',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='lms.subject'),
            preserve_default=False,
        ),
    ]
