# Generated by Django 3.2.8 on 2021-11-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_assignmentcreate_subject_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.teacher'),
        ),
    ]
