# Generated by Django 3.2.8 on 2021-11-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_subject_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='assignment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.assignmentcreate'),
            preserve_default=False,
        ),
    ]
