# Generated by Django 3.2.8 on 2021-11-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
