# Generated by Django 3.2.8 on 2021-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_assignmentsubmit_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcreate',
            name='is_submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
