# Generated by Django 3.2.8 on 2021-11-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_assignmentcreate_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.assignmentcreate'),
        ),
    ]
