# Generated by Django 3.2.8 on 2021-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_assignmentsubmit_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentcreate',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='is_submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
