# Generated by Django 3.2.8 on 2021-11-18 16:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=3, max_length=20),
            preserve_default=False,
        ),
    ]
