# Generated by Django 3.2.8 on 2021-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20211118_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher_class',
        ),
    ]
