# Generated by Django 3.2.8 on 2021-11-18 17:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_auto_20211118_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1, max_length=10),
        ),
    ]
