# Generated by Django 3.2.8 on 2021-12-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_meetingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_created_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
