# Generated by Django 3.2.8 on 2021-12-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_meetingmodel_meeting_created_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_subject',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='lms.subject'),
            preserve_default=False,
        ),
    ]
