# Generated by Django 3.2.8 on 2021-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20211118_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
            preserve_default=False,
        ),
    ]
