# Generated by Django 3.2.8 on 2021-12-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_meetingmodel_meeting_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingmodel',
            name='meeting_class',
        ),
    ]
