# Generated by Django 3.2.8 on 2021-12-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_remove_meetingmodel_meeting_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingmodel',
            old_name='meeting_created_data',
            new_name='meeting_created_date',
        ),
    ]
