# Generated by Django 3.2.8 on 2021-12-20 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_rename_meeting_created_data_meetingmodel_meeting_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingmodel',
            old_name='meeting_url',
            new_name='meeting_join_url',
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_start_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_timezone',
            field=models.CharField(default='europe', max_length=250),
            preserve_default=False,
        ),
    ]
