# Generated by Django 3.2.8 on 2021-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_auto_20211220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='meeting_duration',
            field=models.DurationField(),
        ),
    ]
