# Generated by Django 3.2.8 on 2021-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_meetingmodel_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='meeting_join_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='meetingmodel',
            name='meeting_start_url',
            field=models.URLField(max_length=5000),
        ),
    ]
