export const SignupSuccess = 'SignupSuccess'
export const SignupFailed = 'SignupFailed'
export const LoginSuccess = 'LoginSuccess'
export const LoginFailed = 'LoginFailed'
export const SubjectFetchSuccess = 'SubjectFetchSuccess'
export const SubjectFetchFailed = 'SubjecFetchFailed'